### ISSUE TITLE
when an RPC method throws, it triggers 3 requests

### ISSUE THREAD

**Issue by lhorie** [fusionjs/fusion-plugin-rpc-redux-react#16]
```js
// src/components/test.js
import React from 'react';
import {compose} from 'redux';
import {connect} from 'react-redux';
import {prepared} from 'fusion-react-async';
import {reactor} from '../reactors/vehicle';

const Test = () => <div></div>

const hoc = compose(
  reactor,
  connect(({error}) => ({error})),
  prepared(props => props.test())
);

export default hoc(Test);

// src/rpc/handlers.js
export default () => ({
  test: () => {
    throw new Error('test error');
  },
});
```

**Comment by derekjuber** [comment]
This looks like expected behavior for the way the code was written. One error is the server side rendering the component, the second error is when the client loads the component, and the third error is due to HMR reloading the component again. I don't know why HMR does the second reload but that is a separate issue.

If the hook is removed from prepared and put on an onClick handler, the error is only thrown once as expected.
